version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile or Docker build context
      args:
        - PUBLIC_IP=${PUBLIC_IP}
    ports:
      - "8081:3000"  # Map container port to host port
    depends_on:
      - backend  # Ensure backend container is started first
    env_file:
      - .env
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile or Docker build context
      args:
        - PUBLIC_IP=${PUBLIC_IP}
    env_file:
      - .env
    ports:
      - "8080:8080"  # Map container port to host port